source :rubygems

gem 'eventmachine'
gem 'em-websocket'
gem 'em-http-request'
gem 'http-parser-lite'
gem 'thin'
gem 'sinatra'
gem 'foreman'
gem 'yajl-ruby'
gem 'cuuid'
gem 'swift'
gem 'swift-db-sqlite3'
gem 'haml'
gem 'rdiscount'
